### ISSUE TITLE
Create example

### ISSUE THREAD

**Issue by tenhobi** [jakemac53/built_html#2]
Create a small example to `example/` directory. (index.template.html, build.yaml, pubspec.yaml)

build.yaml file shoud be something like:
```
builders:
  built_html:
    import: 'package:built_html/builder.dart'
    builder_factories: ['createBuilder']
    build_to: cache
    build_extensions:
      '.template.html': ['.html']
```
